import assert from "node:assert/strict";
import test from "node:test";
import { evaluateConditionGraph } from "../scripts/lib/goal-engine/condition-validity.mjs";
const hash = "a".repeat(64);
function projection() { return { goalId: "g", executionRevision: 1, executionContractHash: hash, tasks: new Map([["t", { status: "accepted" }]]), taskApplicability: new Map([["t", { state: "applicable" }]]), conditions: new Map([["a", { definition: { id: "a", depends_on: [], invalidation: { paths: ["src/**"], task_ids: [] }, stability: { mode: "single", require_fresh_environment: true } }, supportingEvidenceIds: ["ea"] }], ["b", { definition: { id: "b", depends_on: [{ kind: "condition", id: "a" }], invalidation: { paths: [], task_ids: [] }, stability: { mode: "single", require_fresh_environment: true } }, supportingEvidenceIds: ["eb"] }]]), evidenceHistory: [{ evidenceId: "ea", conditionId: "a", executionRevision: 1, executionContractHash: hash, conditionHash: hash, world: { head: "h" }, adapter: { ref: "oracle", version: "1" }, environment: { ref: "local", fingerprint: "e" }, fixtures: [{ ref: "sample", fingerprint: "f" }], resource: { key: "cpu", holders: [], capacity: 1 }, run: { runId: "r", state: "terminal" }, sequence: 1, mutationSequence: 0 }, { evidenceId: "eb", conditionId: "b", executionRevision: 1, executionContractHash: hash, conditionHash: hash, world: { head: "h" }, adapter: { ref: "oracle", version: "1" }, environment: { ref: "local", fingerprint: "e" }, fixtures: [{ ref: "sample", fingerprint: "f" }], resource: { key: "cpu", holders: [], capacity: 1 }, run: { runId: "r2", state: "terminal" }, sequence: 2, mutationSequence: 0 }] }; }
const world = { safe: true, repo: { head: "h", trackedDirty: [], untracked: [], sequencer: null }, adapters: [{ ref: "oracle", version: "1" }], environments: [{ ref: "local", fingerprint: "e", available: true }], fixtures: [{ ref: "sample", fingerprint: "f", available: true }], resources: [{ key: "cpu", holders: [], capacity: 1 }], activeRuns: [] };
test("identity-matched current world is fresh and accepted tasks are never mutated", () => { const p = projection(); const result = evaluateConditionGraph({ projection: p, worldSnapshot: world }); assert.equal(result.conditions.get("a").status, "fresh"); assert.equal(result.conditions.get("b").status, "fresh"); assert.equal(result.tasks.get("t").status, "accepted"); assert.notEqual(result.taskApplicability, p.taskApplicability); });
test("unknown or overlapping diff, registry drift, and stale predecessors fail closed", () => { const p = projection(); const changed = { ...world, repo: { ...world.repo, head: "i" }, freshnessProofs: [{ evidenceId: "ea", ancestor: true, known: true, paths: ["src/a"] }, { evidenceId: "eb", ancestor: true, known: true, paths: [] }] }; let result = evaluateConditionGraph({ projection: p, worldSnapshot: changed }); assert.equal(result.conditions.get("a").status, "stale"); assert.equal(result.conditions.get("b").status, "stale"); result = evaluateConditionGraph({ projection: projection(), worldSnapshot: { ...world, adapters: [{ ref: "oracle", version: "2" }] } }); assert.equal(result.conditions.get("a").status, "stale"); });
test("stability rejects duplicate, cross-condition, old-mutation and non-consecutive evidence", () => { const p = projection(); p.conditions.get("a").supportingEvidenceIds = ["ea", "ea"]; assert.equal(evaluateConditionGraph({ projection: p, worldSnapshot: world }).conditions.get("a").status, "stale"); });
