import assert from "node:assert/strict";
import { execFile as execFileCallback } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import test from "node:test";

import { createPlanRunnerDependencies } from "../scripts/lib/plan/plan-runner-dependencies.mjs";
import { applyEvent, createProjection } from "../scripts/lib/plan/plan-events.mjs";
import { createPlanRevisionStore } from "../scripts/lib/plan/plan-revision-store.mjs";

const execFile = promisify(execFileCallback);
const sha = (seed) => seed.repeat(64).slice(0, 64);
async function git(cwd, ...args) { return (await execFile("git", args, { cwd })).stdout.trim(); }
function source(revision, parentPlanHash, changed = "original") { return Buffer.from(`# Recovery fixture\n\n## Execution Contract\n\n\`\`\`json\n{"schemaVersion":"pi-plan.v3","revision":${revision},"parentPlanHash":${JSON.stringify(parentPlanHash)},"verification":[{"id":"test","command":"true","cwd":".","timeoutMs":900000}],"requiredGates":["deterministic","plan-audit","external-review","final-completeness"],"resourceCapacities":{},"executionDefaults":{"agent":"executor","risk":"normal","workflow":{"mode":"inherit-repository"},"timeoutMs":900000},"taskExecution":{"task-1":{},"task-2":{}},"taskAcceptance":{"task-1":{"strategy":"commands","commandIds":["test"]},"task-2":{"strategy":"commands","commandIds":["test"]}}}\n\`\`\`\n\nRecover amendment workspaces after an interrupted approved revision.\n\n### Task 1: Authorization source\n\n**Files:**\n- Modify: \`a.txt\`\n\nAuthorize amendment recovery.\n\n### Task 2: ${changed}\n\n**Files:**\n- Modify: \`b.txt\`\n\nPerform the changed target task.\n`); }
function event(planId, type, data) { return { schemaVersion: "pi-plan-event.v1", eventId: crypto.randomUUID(), planId, occurredAt: "2026-07-29T00:00:00.000Z", type, data }; }
function replay(entries) { return entries.reduce((p, e) => applyEvent(p, e), createProjection()); }

async function fixture({ attempts = ["workspace-allocated"], pointer = "match", inspect = async () => ({ clean: true }), release = async () => {} } = {}) {
  const origin = await mkdtemp(path.join(os.tmpdir(), "pi-amend-recovery-")); const stateRoot = path.join(origin, "state"); const planId = "recovery";
  await git(origin, "init"); await git(origin, "config", "user.email", "test@example.com"); await git(origin, "config", "user.name", "Test"); await writeFile(path.join(origin, "README.md"), "base\n"); await git(origin, "add", "."); await git(origin, "commit", "-m", "base");
  const baseCommit = await git(origin, "rev-parse", "HEAD"); const worktree = path.join(stateRoot, "var", "plan-worktrees", planId); await mkdir(path.dirname(worktree), { recursive: true }); await git(origin, "worktree", "add", "-b", `pi-plan/${planId}`, worktree, baseCommit);
  const store = createPlanRevisionStore({ stateRoot }); const one = await store.prepareRevision({ planId, sourceBytes: source(1, null), reason: "initial-approval", initiator: { kind: "launcher" } }); const two = await store.prepareRevision({ planId, sourceBytes: source(2, one.manifest.planHash, "changed contract"), reason: "scope-approved", initiator: { kind: "supervisor-request", requestId: "auth", taskId: "task-1", attemptId: "auth-attempt", runId: "auth-run" } });
  const r1 = await store.readRevision(planId, 1), r2 = await store.readRevision(planId, 2); if (pointer === "match") await store.writeCurrent(r2);
  const workspace = { originRoot: origin, worktree, baseCommit, headCommit: baseCommit };
  const entries = [event(planId, "plan.created", { workspace, tasks: ["task-1", "task-2"], revision: { number: 1, manifestSha256: r1.manifestSha256, sourceBytesSha256: r1.manifest.sourceBytesSha256, planHash: r1.manifest.planHash, irVersion: r1.manifest.irVersion, irHash: r1.manifest.irHash, taskHashes: r1.manifest.taskHashes } })];
  const authLease = { path: "/auth", branch: "pi-plan-attempt/recovery/task-1/auth", ownerToken: "auth-owner" }; entries.push(event(planId, "attempt.workspace-allocated", { attemptId: "auth-attempt", taskId: "task-1", baseCommit, workspace: authLease }), event(planId, "attempt.dispatch-requested", { attemptId: "auth-attempt", taskId: "task-1", dispatchId: "auth-dispatch", baseCommit, workspace: authLease, tool: { agent: "executor", task: "auth", cwd: "/auth", output: "/auth.out", timeoutMs: 1, context: "fresh", async: true, clarify: false, worktree: false }, toolHash: sha("a"), planIrHash: r1.manifest.irHash, taskHash: r1.manifest.taskHashes["task-1"].effective, schedulingHash: r1.manifest.taskHashes["task-1"].scheduling, dispatchContextHash: sha("b") }), event(planId, "attempt.bound", { attemptId: "auth-attempt", taskId: "task-1", dispatchId: "auth-dispatch", runId: "auth-run", asyncDir: "/auth-async", sessionFile: "/auth.session" }), event(planId, "attempt.attention-requested", { requestId: "auth", taskId: "task-1", attemptId: "auth-attempt", runId: "auth-run", kind: "need_decision", message: "approved", projectionVersion: 5, createdAt: "2026-07-29T00:00:00.000Z" }), event(planId, "attempt.attention-resolved", { attemptId: "auth-attempt", requestId: "auth", runId: "auth-run", expectedProjectionVersion: 5, resolutionSha256: sha("c") }));
  for (const [i, status] of attempts.entries()) { const id = `attempt-${String(i + 1).padStart(2, "0")}`, lease = { path: `/attempts/${id}`, branch: `pi-plan-attempt/recovery/task-2/${i}`, ownerToken: `${id}-owner` }; entries.push(event(planId, "attempt.workspace-allocated", { attemptId: id, taskId: "task-2", baseCommit, workspace: lease })); if (status !== "workspace-allocated") { const tool = { agent: "executor", task: "target", cwd: lease.path, output: `${lease.path}/out`, timeoutMs: 1, context: "fresh", async: true, clarify: false, worktree: false }; entries.push(event(planId, "attempt.dispatch-requested", { attemptId: id, taskId: "task-2", dispatchId: `${id}-dispatch`, baseCommit, workspace: lease, tool, toolHash: sha("d"), planIrHash: r1.manifest.irHash, taskHash: r1.manifest.taskHashes["task-2"].effective, schedulingHash: r1.manifest.taskHashes["task-2"].scheduling, dispatchContextHash: sha("e") })); if (status === "active") entries.push(event(planId, "attempt.bound", { attemptId: id, taskId: "task-2", dispatchId: `${id}-dispatch`, runId: `${id}-run`, asyncDir: `${lease.path}/async`, sessionFile: `${lease.path}/session` })); } }
  const before = replay(entries); entries.push(event(planId, "plan.amended", { revision: 2, parentRevision: 1, manifestSha256: r2.manifestSha256, sourceBytesSha256: r2.manifest.sourceBytesSha256, planHash: r2.manifest.planHash, irHash: r2.manifest.irHash, taskHashes: r2.manifest.taskHashes, diff: { added: [], changed: ["task-2"], rebound: [], retired: [], unchanged: ["task-1"] }, supersededAttemptIds: attempts.map((_, i) => `attempt-${String(i + 1).padStart(2, "0")}`), requestId: "auth", reason: "approved recovery" })); replay(entries);
  const calls = { supersede: [], recoverDispatch: [], recoverBinding: [], release: [], inspect: [], spawn: [] }; const backend = { async spawn(x) { calls.spawn.push(x); }, async supersede(x) { calls.supersede.push(x); return { kind: "terminal", dispatchId: x.dispatchId, runId: `${x.attemptId}-run`, asyncDir: `/attempts/${x.attemptId}/async`, artifactSha256: sha("f") }; }, async recoverDispatch(x) { calls.recoverDispatch.push(x); }, async recoverBinding(x) { calls.recoverBinding.push(x); } };
  const revisionStore = { readRevision: (...args) => store.readRevision(...args), readCurrent: (...args) => store.readCurrent(...args), writeCurrent: (...args) => store.writeCurrent(...args) }; const deps = createPlanRunnerDependencies({ pi: { async appendEntry(_type, data) { entries.push(data); } }, originRoot: origin, stateRoot, revisionStore, executionBackend: backend, inspectAttemptWorkspace: async (x) => { calls.inspect.push(x); return inspect(x); }, releaseAttemptWorkspace: async (x, o) => { calls.release.push([x, o]); return release(x, o); } });
  return { origin, store, revisionStore, r2, entries, ctx: { cwd: worktree, sessionManager: { getBranch: () => entries.map((data) => ({ customType: "pi-plan-event-v1", data })) } }, deps, calls };
}
function appended(f) { return f.deps.currentProjection ? [] : f.entries; }
function types(f) { return f.entries.map((e) => e.type); }

test("recovery replays workspace-allocated supersede through cleanup without rewriting matching pointer", async (t) => { const f = await fixture(); t.after(() => rm(f.origin, { recursive: true, force: true })); let writes = 0; const original = f.revisionStore.writeCurrent.bind(f.revisionStore); f.revisionStore.writeCurrent = async (...x) => { writes++; return original(...x); }; await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); assert.equal(writes, 0); assert.deepEqual(types(f).slice(-2), ["attempt.superseded", "attempt.workspace-released"]); assert.equal(f.calls.supersede.length, 0); assert.equal(f.calls.inspect.length, 1); assert.equal(f.calls.release[0][1].disposition, "superseded-cleanup"); assert.equal(replay(f.entries).attempts.get("attempt-01").workspaceReleased, true); });

test("dirty, inspection failure, and terminal proof preserve workspace", async (t) => { for (const inspect of [async () => ({ clean: false }), async () => { throw new Error("inspect"); }]) { const f = await fixture({ inspect }); t.after(() => rm(f.origin, { recursive: true, force: true })); await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); assert.equal(replay(f.entries).attempts.get("attempt-01").workspaceDisposition, "superseded-preserve"); } const f = await fixture({ attempts: ["dispatch-requested"] }); t.after(() => rm(f.origin, { recursive: true, force: true })); await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); assert.equal(replay(f.entries).attempts.get("attempt-01").workspaceDisposition, "superseded-preserve"); assert.equal(f.calls.inspect.length, 0); });

test("recovery resumes superseded checkpoint without backend and retries durable proof/release stages", async (t) => { const f = await fixture(); t.after(() => rm(f.origin, { recursive: true, force: true })); await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); f.entries.pop(); await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); assert.equal(f.calls.supersede.length, 0); assert.equal(types(f).filter((x) => x === "attempt.superseded").length, 1); assert.equal(types(f).filter((x) => x === "attempt.workspace-released").length, 0); });

test("NOT_FOUND dispatch and active binding recover exact persisted identity without spawn", async (t) => { const f = await fixture({ attempts: ["dispatch-requested"] }); t.after(() => rm(f.origin, { recursive: true, force: true })); let first = true; f.deps = createPlanRunnerDependencies({ pi: { async appendEntry(_type, data) { f.entries.push(data); } }, originRoot: f.origin, stateRoot: path.join(f.origin, "state"), revisionStore: f.revisionStore, executionBackend: { async supersede(x) { if (first) { first = false; const e = new Error("missing"); e.code = "EXECUTION_DISPATCH_NOT_FOUND"; throw e; } return { kind: "terminal", dispatchId: x.dispatchId, runId: `${x.attemptId}-run`, asyncDir: `/attempts/${x.attemptId}/async`, artifactSha256: sha("f") }; }, async recoverDispatch(x) { f.calls.recoverDispatch.push(x); }, async recoverBinding(x) { f.calls.recoverBinding.push(x); }, async spawn(x) { f.calls.spawn.push(x); } }, inspectAttemptWorkspace: async () => ({ clean: false }), releaseAttemptWorkspace: async () => {} }); await f.deps.recoverSupersededAttempts({ ctx: f.ctx }); assert.deepEqual(Object.keys(f.calls.recoverDispatch[0]).sort(), ["agent", "attemptId", "cwd", "dispatchId", "output", "task", "timeoutMs"]); assert.equal(f.calls.spawn.length, 0); });

test("pointer repair failure aggregates while sorted attempts continue, and lifecycle fences stop domain action", async (t) => { const f = await fixture({ attempts: ["workspace-allocated"], pointer: "missing" }); t.after(() => rm(f.origin, { recursive: true, force: true })); f.revisionStore.writeCurrent = async () => { throw new Error("pointer"); }; await assert.rejects(f.deps.recoverSupersededAttempts({ ctx: f.ctx }), AggregateError); assert.deepEqual(f.calls.release.map(([x]) => x.path), ["/attempts/attempt-01"]); assert.equal(types(f).filter((x) => x === "plan.amended").length, 1); const g = await fixture({ pointer: "missing" }); t.after(() => rm(g.origin, { recursive: true, force: true })); g.revisionStore.writeCurrent = async () => { throw new Error("pointer"); }; await assert.rejects(g.deps.blockPlan({ reason: "no" }, { ctx: g.ctx }), AggregateError); assert.equal(types(g).includes("plan.blocked"), false); });
