import { spawn, execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, realpathSync, mkdirSync, readFileSync, writeFileSync, renameSync, unlinkSync, rmSync, readdirSync, lstatSync, chmodSync } from "node:fs";
import path from "node:path";
import { createManagedWorktree, releaseManagedWorktree } from "../worktree-lifecycle/managed-worktree.mjs";
import { markDisposition } from "../worktree-lifecycle/registry.mjs";
import { captureProcessBirthIdentity } from "../subagent-dispatch/process-birth-identity.ts";

const ID=/^[A-Za-z0-9][A-Za-z0-9._-]*$/; const PLAN_KEYS=["schema","limits","actions"], LIMIT_KEYS=["timeoutMs","maxOutputBytes","terminationGraceMs","maxConcurrentWorkspaces"], ACTION_KEYS=["id","kind","executable","args"];
const LEASE_KEYS=["schema","id","originRoot","stateRoot","goalId","taskId","attempt","integratedHead","path","branch","ownerToken","plan","planHash","state","runtime","lastRun"];
function git(cwd,...args){return execFileSync("git",args,{cwd,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim()}
function exact(v,k){return v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(x=>Object.hasOwn(v,x))}
function safe(v,n){if(typeof v!=="string"||!ID.test(v))throw Error(`Invalid ${n}`);return v}
function hash(v){return createHash("sha256").update(JSON.stringify(v)).digest("hex")}; function freeze(v){return Object.freeze(structuredClone(v))}
function allocationId(root,g,t,a){return `validation-${createHash("sha256").update(`${root}\0${g}\0${t}\0${a}`).digest("hex")}`}; function leasePath(root,id){return path.join(root,"validation-leases",`${id}.json`)}
function regular(file, mode=0o600){const s=lstatSync(file); if(s.isSymbolicLink()||!s.isFile()||(s.mode&0o777)!==mode)throw Error("Validation lease file identity is invalid")}
function leaseDir(root){const d=path.join(root,"validation-leases"); if(existsSync(d)){const s=lstatSync(d);if(s.isSymbolicLink()||!s.isDirectory())throw Error("Validation lease directory is invalid")}else mkdirSync(d,{recursive:true,mode:0o700}); return d}
function readLease(root,id){const file=leasePath(root,id); try{regular(file);const v=JSON.parse(readFileSync(file,"utf8"));if(!exact(v,LEASE_KEYS)||v.schema!=="dispatch-ir.v1.validation-lease"||v.planHash!==hash(v.plan)||!new Set(["active","running","cleanup-debt","released"]).has(v.state))throw Error();return v}catch(e){throw Error(`Validation lease is invalid: ${e.message}`)}}
function writeLease(v,create=false){const d=leaseDir(v.stateRoot),file=leasePath(v.stateRoot,v.id),tmp=path.join(d,`.${v.id}.${process.pid}.${Date.now()}`);writeFileSync(tmp,JSON.stringify(v),{mode:0o600,flag:"wx"});chmodSync(tmp,0o600);try{if(create&&existsSync(file))throw Error("Validation lease already exists"); if(!create&&existsSync(file))regular(file);renameSync(tmp,file);regular(file)}finally{try{unlinkSync(tmp)}catch{}}}
function validatePlan(p){if(!exact(p,PLAN_KEYS)||p.schema!=="dispatch-ir.v1.validation-plan"||!exact(p.limits,LIMIT_KEYS)||!Array.isArray(p.actions)||p.actions.length<1||p.actions.length>16)throw Error("Invalid validation plan");const l=p.limits;if(!Number.isInteger(l.timeoutMs)||l.timeoutMs<50||l.timeoutMs>1800000||!Number.isInteger(l.maxOutputBytes)||l.maxOutputBytes<1||l.maxOutputBytes>1000000||!Number.isInteger(l.terminationGraceMs)||l.terminationGraceMs<50||l.terminationGraceMs>5000||!Number.isInteger(l.maxConcurrentWorkspaces)||l.maxConcurrentWorkspaces<1||l.maxConcurrentWorkspaces>4)throw Error("Invalid validation limits");let seen=new Set(),ok=false;for(const a of p.actions){if(!exact(a,ACTION_KEYS)||!ID.test(a.id)||seen.has(a.id)||!["setup","validation"].includes(a.kind)||typeof a.executable!=="string"||!path.isAbsolute(a.executable)||!Array.isArray(a.args)||a.args.some(x=>typeof x!=="string"||x.includes("\0")||Buffer.byteLength(x)>8192))throw Error("Invalid validation action");seen.add(a.id);ok ||=a.kind==="validation"}if(!ok)throw Error("Validation plan requires validation action");return structuredClone(p)}
function managed(lease){const file=path.join(lease.originRoot,".state","worktree-lifecycle","leases",`${lease.id}.json`);let m;try{regular(file);m=JSON.parse(readFileSync(file,"utf8"))}catch{throw Error("Managed identity is invalid")}if(m.ownerKind!=="goal-validation"||m.ownerId!==lease.id||m.ownerToken!==lease.ownerToken||m.originRoot!==lease.originRoot||m.path!==lease.path||m.branchRef!==`refs/heads/${lease.branch}`||m.baseCommit!==lease.integratedHead||m.headCommit!==lease.integratedHead||m.state!=="active")throw Error("Managed owner identity mismatch");try { const top=realpathSync(git(lease.path,"rev-parse","--show-toplevel"));if(top!==lease.path||git(lease.path,"symbolic-ref","-q","HEAD")!==m.branchRef||git(lease.path,"rev-parse","HEAD")!==lease.integratedHead||git(lease.path,"status","--porcelain=v1","-z")!=="")throw Error("Managed Git identity mismatch");const list=git(lease.originRoot,"worktree","list","--porcelain");if(!list.includes(`worktree ${lease.path}`)||!list.includes(`branch ${m.branchRef}`))throw Error("Managed Git registration mismatch"); } catch { throw Error("Managed Git identity mismatch"); } return m}
function activeLeases(root){const d=path.join(root,"validation-leases");if(!existsSync(d))return[];const s=lstatSync(d);if(s.isSymbolicLink()||!s.isDirectory())throw Error("Validation lease store unavailable");return readdirSync(d).filter(x=>x.endsWith(".json")).map(x=>readLease(root,x.slice(0,-5))).filter(x=>x.state!=="released")}
export function createValidationWorkspace(input={}){if(!exact(input,["originRoot","stateRoot","goalId","taskId","attempt","integratedHead","validationPlan"])&&!exact(input,["originRoot","stateRoot","goalId","taskId","attempt","integratedHead","validationPlan","originRef"]))throw Error("Invalid validation allocation");let {originRoot,stateRoot,goalId,taskId,attempt,integratedHead,validationPlan,originRef="HEAD"}=input;safe(goalId,"goalId");safe(taskId,"taskId");if(!Number.isInteger(attempt)||attempt<1||typeof stateRoot!=="string"||!path.isAbsolute(stateRoot))throw Error("Invalid validation allocation");if(!/^[a-f0-9]{40}$/.test(integratedHead))throw Error("integratedHead must be a full SHA");const plan=validatePlan(validationPlan),root=realpathSync(originRoot),sr=realpathSync(stateRoot);if(git(root,"rev-parse","--verify",`${originRef}^{commit}`)!==integratedHead)throw Error("integratedHead must be the current full commit SHA");const id=allocationId(root,goalId,taskId,attempt),all=activeLeases(sr);if(all.some(x=>x.goalId===goalId&&x.taskId===taskId)||all.length>=Math.min(plan.limits.maxConcurrentWorkspaces,...all.map(x=>x.plan.limits.maxConcurrentWorkspaces)))throw Error("Validation lease capacity conflict");const lease={schema:"dispatch-ir.v1.validation-lease",id,originRoot:root,stateRoot:sr,goalId,taskId,attempt,integratedHead,path:path.resolve(sr,"validation-worktrees",`${goalId}-${taskId}-${attempt}`),branch:`ge-validation/${goalId}/${taskId}/${attempt}`,ownerToken:null,plan,planHash:hash(plan),state:"active",runtime:null,lastRun:null};writeLease(lease,true);try{const m=createManagedWorktree({originRoot:root,id,branch:lease.branch,baseCommit:integratedHead,path:lease.path,owner:{kind:"goal-validation",id}});lease.ownerToken=m.ownerToken;lease.path=m.path;writeLease(lease);managed(lease);return freeze({...lease,validationPlan:plan})}catch(e){lease.state="cleanup-debt";try{writeLease(lease)}catch{}throw e}}
function loaded(u, running=false){if(!u||typeof u.id!=="string"||typeof u.stateRoot!=="string")throw Error("Invalid validation lease receipt");const l=readLease(realpathSync(u.stateRoot),u.id);for(const k of ["originRoot","stateRoot","path","ownerToken","integratedHead","planHash"])if(u[k]!==l[k])throw Error("Validation lease receipt mismatch");if(l.state!==(running?"running":"active"))throw Error("Validation lease is not active");managed(l);return l}
function env(home,tmp){let e={};for(const k of ["PATH","LANG","LC_ALL","TZ"])if(process.env[k])e[k]=process.env[k];return{...e,CI:"1",HOME:home,TMPDIR:tmp}}
function group(p){try{return execFileSync("ps",["-axo","pid=,pgid="],{encoding:"utf8"}).split("\n").map(x=>x.trim().split(/\s+/)).filter(x=>/^\d+$/.test(x[0])&&x[1]===String(p)).map(x=>+x[0])}catch{return null}}
async function teardown(pid,grace){const before=group(pid);if(!before)throw Error("Process group probe unavailable");try{process.kill(-pid,"SIGTERM")}catch{}await new Promise(r=>setTimeout(r,grace));let now=group(pid);if(!now)throw Error("Process group probe unavailable");if(now.length){try{process.kill(-pid,"SIGKILL")}catch{}for(let i=0;i<30&&now.length;i++){await new Promise(r=>setTimeout(r,20));now=group(pid);if(!now)throw Error("Process group probe unavailable")}}if(now.length)throw Error("Process group is not terminal");return createHash("sha256").update(JSON.stringify({pgid:pid,before,terminal:"empty"})).digest("hex")}
async function runCleanValidationAsync(input={}){let lease=loaded(input.lease),action=lease.plan.actions.find(a=>a.id===input.actionId);if(!action)throw Error("Unknown validation action");const runtime=path.join(lease.stateRoot,"validation-runtime",`${lease.id}-${Date.now()}`);mkdirSync(runtime,{recursive:true,mode:0o700});const home=path.join(runtime,"home"),tmp=path.join(runtime,"tmp");mkdirSync(home,{mode:0o700});mkdirSync(tmp,{mode:0o700});lease.state="running";lease.runtime={path:runtime,actionId:action.id,pid:null,pidBirthIdentity:null};writeLease(lease);let child;try{child=spawn(action.executable,action.args,{cwd:lease.path,detached:true,stdio:["ignore","pipe","pipe"],env:env(home,tmp)});await new Promise((resolve,reject)=>{child.once("spawn",resolve);child.once("error",reject)})}catch(e){lease.state="cleanup-debt";try{writeLease(lease)}catch{}throw e}let identity;try{identity=await captureProcessBirthIdentity(child.pid);lease.runtime={...lease.runtime,pid:child.pid,pidBirthIdentity:identity};writeLease(lease)}catch(e){lease.state="cleanup-debt";try{writeLease(lease)}catch{}throw e}let chunks=[],bytes=0,truncated=false,timed=false,code=null,signal=null;const add=x=>{const b=Buffer.from(x),n=Math.max(0,lease.plan.limits.maxOutputBytes-bytes);chunks.push(b.subarray(0,n));bytes+=Math.min(n,b.length);truncated ||=b.length>n};child.stdout.on("data",add);child.stderr.on("data",add);const closed=new Promise((resolve)=>{ child.once("close",(c,s)=>{ code=c; signal=s; resolve(); }); });const timeout=new Promise(r=>setTimeout(()=>{timed=true;r()},lease.plan.limits.timeoutMs));await Promise.race([closed,timeout]);let proof;try{if(await captureProcessBirthIdentity(child.pid).catch(()=>null) && !group(child.pid)?.includes(child.pid))throw Error("Process birth identity conflict");proof=await teardown(child.pid,lease.plan.limits.terminationGraceMs);managed(readLease(lease.stateRoot,lease.id));lease=readLease(lease.stateRoot,lease.id);lease.state="active";lease.lastRun={actionId:action.id,status:timed?"timed_out":code===0?"passed":"failed"};lease.runtime=null;writeLease(lease);rmSync(runtime,{recursive:true,force:true})}catch(e){lease.state="cleanup-debt";try{writeLease(lease)}catch{}throw e}return{status:timed?"timed_out":code===0?"passed":"failed",code,signal,output:Buffer.concat(chunks).toString("utf8"),outputBytes:bytes,truncated,terminal:true,pid:child.pid,pidBirthIdentity:identity,processGroupTerminalProof:proof,workspaceClean:true}}
export function runCleanValidation(input={}) { if(!exact(input,["lease","actionId"])||typeof input.actionId!=="string")throw Error("runCleanValidation accepts only lease and actionId"); let lease; try { lease=loaded(input.lease); } catch(error) { return Promise.reject(error); } if(!lease.plan.actions.some((action)=>action.id===input.actionId))throw Error("Unknown validation action"); return runCleanValidationAsync(input); }
export function releaseValidationWorkspace(u,{expectedHead}={}){const l=loaded(u);if(expectedHead!==l.integratedHead)throw Error("Validation release identity mismatch");try{const r=markDisposition({originRoot:l.originRoot,id:l.id,ownerToken:l.ownerToken,disposition:"reclaimable"});if(r.headCommit!==expectedHead)throw Error("Validation release HEAD identity mismatch");const out=releaseManagedWorktree({originRoot:l.originRoot,id:l.id,ownerToken:l.ownerToken});l.state="released";writeLease(l);return out}catch(e){l.state="cleanup-debt";try{writeLease(l)}catch{}throw e}}
