import { createHash, randomUUID } from "node:crypto";
import { constants, closeSync, fstatSync, lstatSync, openSync, readFileSync } from "node:fs";
import { prepareManagedValidation, startManagedValidation, inspectManagedValidation, recoverManagedValidation, releaseManagedValidation } from "./managed-validation.mjs";
import { deriveObservationVerdict, materializeConditionEvidence } from "./condition-evidence.mjs";
import { hostObservationAdapter } from "./observation-adapters.mjs";
const exact=(v,k)=>v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(x=>Object.hasOwn(v,x));
const hash=v=>createHash("sha256").update(JSON.stringify(v)).digest("hex"); const frozen=v=>Object.freeze(structuredClone(v));
const phases=["requested","lease_allocated","process_bound","terminal","recorded","released","cleanup_debt"];
const active=new Set(phases.slice(0,5));
function condition(projection,id){const c=projection?.conditions instanceof Map?projection.conditions.get(id):projection?.conditions?.[id];if(!c?.definition||!c.definition.oracle_ref)throw Error("Condition is not observable");return c;}
function world(snapshot){if(!snapshot||snapshot.safe!==true||snapshot.repo?.head===undefined&&snapshot.head===undefined)throw Error("Current world is not safe and fresh");return snapshot;}
function event(type,data){return frozen({type,data:structuredClone(data)});}
function receiptBase(projection,c,conditionId,worldSnapshot,adapter,runId){return {schema:"dispatch-ir.v1.observation-receipt",runId,conditionId,cycle:0,goalId:projection.goalId,executionRevision:projection.executionRevision,executionContractHash:projection.executionContractHash,conditionHash:hash(c.definition),worldSnapshotHash:hash(worldSnapshot),resourceClaimsHash:hash(adapter.resourceClaims),adapter:{ref:adapter.ref,version:adapter.version},phase:"requested",managedReceipt:null,terminal:null,recorded:null,cleanupDebt:false};}
function registryAdapter(c,services){if(!services?.adapterRegistry)throw Error("Host adapter registry required");return hostObservationAdapter(services.adapterRegistry,c.definition.oracle_ref);}
function noActive(projection,conditionId,adapter){const runs=projection?.observationRuns instanceof Map?[...projection.observationRuns.values()]:Object.values(projection?.observationRuns||{});if(runs.some(r=>r.conditionId===conditionId&&active.has(r.phase)))throw Error("Condition already has an active observation");const holders=projection?.resourceHolders||[];if(holders.some(h=>adapter.resourceClaims.some(c=>c.key===h.key)))throw Error("Observation resource conflict");}
export function requestObservation(input={}){if(!exact(input,["projection","conditionId","worldSnapshot","services"])&& !exact(input,["projection","conditionId","worldSnapshot","services","cycle"]))throw Error("Invalid observation request or caller authority");const {projection,conditionId,worldSnapshot,services}=input;if(projection?.runtimeState!=="active")throw Error("Runtime is not active");const c=condition(projection,conditionId);world(worldSnapshot);const adapter=registryAdapter(c,services);if(c.definition.stability?.mode==="single"&&!adapter.deterministic)throw Error("Non-deterministic adapter cannot satisfy single stability");noActive(projection,conditionId,adapter);const runId=`observation-${randomUUID()}`, r=receiptBase(projection,c,conditionId,worldSnapshot,adapter,runId);r.cycle=input.cycle??0;if(!Number.isSafeInteger(r.cycle)||r.cycle<0)throw Error("Invalid observation cycle");const data={runId,conditionId,cycle:r.cycle,worldSnapshotHash:r.worldSnapshotHash,resourceClaimsHash:r.resourceClaimsHash};return frozen({runReceipt:r,event:event("condition.observation_requested",data)});}
function managed(services){return {prepareManagedValidation:services?.prepareManagedValidation||prepareManagedValidation,startManagedValidation:services?.startManagedValidation||startManagedValidation,inspectManagedValidation:services?.inspectManagedValidation||inspectManagedValidation,recoverManagedValidation:services?.recoverManagedValidation||recoverManagedValidation,releaseManagedValidation:services?.releaseManagedValidation||releaseManagedValidation};}
function bound(r,phase,extra={}){return frozen({...r,phase,...extra});}
function planEvents(r){const p=[];if(r.managedReceipt){p.push(event("condition.observation_lease_allocated",{runId:r.runId,conditionId:r.conditionId,allocationId:r.managedReceipt.id,leaseReceiptHash:hash(r.managedReceipt)}));}if(r.terminal?.pidBirthIdentity){p.push(event("condition.observation_process_bound",{runId:r.runId,conditionId:r.conditionId,processIdentityHash:hash({pid:r.terminal.pid,pidBirthIdentity:r.terminal.pidBirthIdentity})}));}if(r.terminal){p.push(event("condition.observation_terminal",{runId:r.runId,conditionId:r.conditionId,terminalProofHash:hash(r.terminal)}));}return p;}
export async function startObservation(requestReceipt,services={}){if(!requestReceipt||requestReceipt.phase!=="requested")throw Error("Observation must start from requested");if(services.assertRequestDurable?.(requestReceipt)!==true)throw Error("Durable request event proof required");const m=managed(services);let prepared;try{prepared=m.prepareManagedValidation({ownerKind:"goal-observation",ownerId:requestReceipt.runId,originRoot:services.originRoot,stateRoot:services.stateRoot,integratedHead:services.integratedHead,plan:hostObservationAdapter(services.adapterRegistry,requestReceipt.adapter.ref).validationPlan,resourceClaims:hostObservationAdapter(services.adapterRegistry,requestReceipt.adapter.ref).resourceClaims});}catch(error){if(/conflict/i.test(error.message))return frozen({status:"blocked",runReceipt:bound(requestReceipt,"requested"),events:[]});throw error;}let terminal;try{terminal=await m.startManagedValidation(prepared);}catch(error){return frozen({status:"attention",runReceipt:bound(requestReceipt,"cleanup_debt",{managedReceipt:prepared,cleanupDebt:true}),events:[]});}const r=bound(requestReceipt,"terminal",{managedReceipt:prepared,terminal:terminal.terminal});return frozen({status:"terminal",runReceipt:r,events:planEvents(r)});}
export function inspectObservation(runReceipt,services={}){if(!runReceipt||!phases.includes(runReceipt.phase))throw Error("Invalid observation receipt");if(!runReceipt.managedReceipt)return frozen(runReceipt);const state=managed(services).inspectManagedValidation(runReceipt.managedReceipt);if(state.cleanupDebt)return bound(runReceipt,"cleanup_debt",{cleanupDebt:true});return frozen(runReceipt);}
export async function recoverObservation(runReceipt,services={}){if(!runReceipt||!phases.includes(runReceipt.phase))throw Error("Invalid observation receipt");if(!runReceipt.managedReceipt)return frozen(runReceipt);const state=await managed(services).recoverManagedValidation(runReceipt.managedReceipt);if(state.cleanupDebt||state.phase==="cleanup_debt")return bound(runReceipt,"cleanup_debt",{cleanupDebt:true});return frozen(runReceipt);}
function canonicalArtifact(ref){if(!exact(ref,["id","path"])||typeof ref.id!=="string"||typeof ref.path!=="string")throw Error("Invalid artifact reference");const before=lstatSync(ref.path);if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||(before.mode&0o777)!==0o600)throw Error("Artifact identity invalid");const fd=openSync(ref.path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=fstatSync(fd),text=readFileSync(fd,"utf8"),after=lstatSync(ref.path);if(opened.dev!==before.dev||opened.ino!==before.ino||after.dev!==before.dev||after.ino!==before.ino)throw Error("Artifact changed during read");return {id:ref.id,text,hash:createHash("sha256").update(text).digest("hex")};}finally{closeSync(fd);}}
export function recordObservation(input={}){if(!exact(input,["projection","runReceipt","artifactRef","worldSnapshot","services"]))throw Error("Invalid observation record or caller authority");const {projection,runReceipt,artifactRef,worldSnapshot,services}=input;if(!runReceipt||runReceipt.phase!=="terminal"||!runReceipt.terminal||runReceipt.cleanupDebt)throw Error("Observation is not a recordable terminal");const prior=projection?.observationRuns instanceof Map?projection.observationRuns.get(runReceipt.runId):projection?.observationRuns?.[runReceipt.runId];if(prior?.phase==="recorded"&&prior.evidenceId)return frozen({runReceipt:bound(runReceipt,"recorded",{recorded:{evidenceId:prior.evidenceId}}),event:null,alreadyRecorded:true});world(worldSnapshot);const artifact=canonicalArtifact(artifactRef),adapter=hostObservationAdapter(services?.adapterRegistry,runReceipt.adapter.ref);let parsed;try{parsed=JSON.parse(artifact.text)}catch{parsed={code:adapter.artifactClassifier.infrastructure_error}}const code=typeof parsed.code==="string"?parsed.code:adapter.artifactClassifier.infrastructure_error;const outcome=Object.entries(adapter.artifactClassifier).find(([,v])=>v===code)?.[0]||"inconclusive";const normalizedOutcome=outcome==="pass"?"passed":outcome==="fail"?"failed":outcome;const identity={goalId:runReceipt.goalId,conditionId:runReceipt.conditionId,executionRevision:runReceipt.executionRevision,executionContractHash:runReceipt.executionContractHash,conditionHash:runReceipt.conditionHash,head:worldSnapshot.repo?.head||worldSnapshot.head,adapter:runReceipt.adapter,environment:services.environment,fixtures:services.fixtures||[],runId:runReceipt.runId,terminalProofHash:hash(runReceipt.terminal),artifact:{id:artifact.id,hash:artifact.hash}};const evidence={...identity,artifact:{...identity.artifact,classifier:{code}}};const verdict=deriveObservationVerdict(evidence,{expectedIdentity:identity,resolvedClassifier:{code,outcome:normalizedOutcome}});const cas=materializeConditionEvidence({stateRoot:services.stateRoot,evidence,expectedIdentity:identity});const r=bound(runReceipt,"recorded",{recorded:{evidenceId:cas.evidenceId,artifactHash:artifact.hash,verdict}});return frozen({runReceipt:r,event:event("condition.observation_recorded",{runId:r.runId,conditionId:r.conditionId,evidenceId:cas.evidenceId,verdict:verdict.kind}),verdict,blocked:verdict.kind==="inconclusive"||verdict.kind==="infrastructure_error",cycleZeroCalibration:r.cycle===0&&verdict.kind==="failed"});}
export function releaseObservation(runReceipt,services={}){if(!runReceipt||runReceipt.phase!=="recorded"||!runReceipt.recorded||!runReceipt.terminal||runReceipt.cleanupDebt)throw Error("Observation requires recorded terminal proof before release");try{const released=managed(services).releaseManagedValidation(runReceipt.managedReceipt,{expectedHead:services.integratedHead});const r=bound(runReceipt,"released",{releaseReceiptHash:hash(released)});return frozen({runReceipt:r,event:event("condition.observation_released",{runId:r.runId,conditionId:r.conditionId,releaseReceiptHash:r.releaseReceiptHash})});}catch(error){return frozen({runReceipt:bound(runReceipt,"cleanup_debt",{cleanupDebt:true}),status:"attention"});}}
