import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { resolve } from "node:path";
import { releaseManagedWorktree } from "./managed-worktree.mjs";

const MANIFEST_KEYS = ["schemaVersion", "id", "ownerKind", "ownerId", "ownerToken", "originRoot", "gitCommonDir", "path", "branchRef", "baseCommit", "headCommit", "state", "createdAt", "updatedAt", "disposition", "lastError"];
const MANIFEST_STATES = new Set(["allocating", "active", "reclaimable", "preserved", "cleanup-debt", "released"]);
const CODE = { main: null, active: "WORKTREE_OWNER_ACTIVE", reclaimable: "WORKTREE_CLEANUP_DEBT", preserved: "WORKTREE_PRESERVED", dirty: "WORKTREE_DIRTY", sequencer: "WORKTREE_SEQUENCER_ACTIVE", "cleanup-debt": "WORKTREE_CLEANUP_DEBT", unmanaged: "WORKTREE_UNMANAGED", missing: "WORKTREE_IDENTITY_MISMATCH", mismatch: "WORKTREE_IDENTITY_MISMATCH", released: null };

export function parseWorktreePorcelain(text) { const records = []; let current; for (const entry of String(text).split("\0")) { if (!entry) continue; const n = entry.indexOf(" "); const key = n < 0 ? entry : entry.slice(0, n); const value = n < 0 ? "" : entry.slice(n + 1); if (key === "worktree") { current = { path: value }; records.push(current); } else if (current) current[key] = key === "bare" || key === "detached" ? true : value || true; } return records; }
function run(cwd, args, kind, probe) { const injected = probe?.({ kind, cwd, args }); if (injected) return injected; try { return { ok: true, stdout: execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], env: { ...process.env, GIT_OPTIONAL_LOCKS: "0" } }), stderr: "" }; } catch { return { ok: false, stdout: "", stderr: "" }; } }
function exactKeys(x) { return x && typeof x === "object" && !Array.isArray(x) && JSON.stringify(Object.keys(x).sort()) === JSON.stringify([...MANIFEST_KEYS].sort()); }
function safeManifest(root, file) {
  const path = resolve(root, ".state/worktree-lifecycle/leases", file);
  try { const st = lstatSync(path); if (!st.isFile() || st.isSymbolicLink()) throw Error(); const m = JSON.parse(readFileSync(path, "utf8")); if (m.schemaVersion === 1 && typeof m.path === "string" && typeof m.state === "string") return { manifest: m, legacy: true }; if ((st.mode & 0o777) !== 0o600 || !exactKeys(m) || m.schemaVersion !== "worktree-lifecycle.owner.v1" || !MANIFEST_STATES.has(m.state) || typeof m.id !== "string" || typeof m.path !== "string" || typeof m.originRoot !== "string" || typeof m.gitCommonDir !== "string" || typeof m.branchRef !== "string" || !m.branchRef.startsWith("refs/heads/") || typeof m.ownerToken !== "string") throw Error(); return { manifest: m }; } catch { return { invalid: true, id: file.replace(/\.json$/, "") }; }
}
function manifests(root) { const dir = resolve(root, ".state/worktree-lifecycle/leases"); try { return readdirSync(dir).filter((x) => x.endsWith(".json")).map((x) => safeManifest(root, x)); } catch { return []; } }
function identity(root, registration, owner, probe) { if (!owner || !registration || !existsSync(registration.path)) return Boolean(owner && registration); try { const top = run(registration.path, ["rev-parse", "--show-toplevel"], "identity", probe); const common = run(registration.path, ["rev-parse", "--git-common-dir"], "identity", probe); const branch = run(registration.path, ["symbolic-ref", "-q", "HEAD"], "identity", probe); const head = run(registration.path, ["rev-parse", "--verify", "HEAD^{commit}"], "identity", probe); if (![top, common, branch, head].every((x) => x.ok)) return false; const commonPath = resolve(registration.path, common.stdout.trim()); return realpathSync(registration.path) === owner.path && realpathSync(top.stdout.trim()) === owner.path && realpathSync(commonPath) === owner.gitCommonDir && branch.stdout.trim() === owner.branchRef && head.stdout.trim() === owner.headCommit && registration.branch === owner.branchRef && owner.originRoot === root; } catch { return false; } }
export function classifyWorktreeFact(fact) { let state = "active"; if (fact.probeFailed || fact.mismatch || fact.registration?.locked || fact.owner?.state === "cleanup-debt") state = "cleanup-debt"; else if (fact.main) state = "main"; else if (!fact.pathExists) state = "missing"; else if (fact.active) state = "active"; else if (fact.operation) state = "sequencer"; else if (fact.clean === false) state = "dirty"; else if (!fact.owner) state = "unmanaged"; else if (fact.owner.state === "preserved") state = "preserved"; else if (fact.owner.state === "reclaimable" && fact.clean === true && fact.identity !== false) state = "reclaimable"; const reasons = []; if (fact.probeFailed) reasons.push("probe-failed"); if (fact.operation) reasons.push(`sequencer:${fact.operation}`); if (fact.clean === false) reasons.push("dirty"); if (!fact.owner && !fact.main) reasons.push("no-owner"); return { state, reasons, automaticAction: state === "reclaimable" ? "release-worktree-only" : "none" }; }
function publicFact(fact) { const c = classifyWorktreeFact(fact); return { registration: fact.registration, path: fact.registration?.path ?? fact.owner?.path, id: fact.owner?.id, owner: fact.owner ? { kind: fact.owner.ownerKind, id: fact.owner.ownerId } : undefined, resources: `${fact.pathExists ? "1" : "0"}${fact.registration ? "1" : "0"}${fact.owner ? "1" : "0"}`, ...c, code: fact.mismatch ? CODE.mismatch : CODE[c.state], severity: c.state === "reclaimable" || c.state === "cleanup-debt" ? "warning" : "diagnostic" }; }
export async function inventoryRepositoryWorktrees({ originRoot, activeProcessCwds = [], probe } = {}) { const root = resolve(originRoot); const listed = run(root, ["worktree", "list", "--porcelain", "-z"], "list", probe); if (!listed.ok) return [publicFact({ registration: { path: root }, main: true, pathExists: existsSync(root), probeFailed: true })]; const owners = manifests(root); const registrations = parseWorktreePorcelain(listed.stdout); const facts = registrations.map((registration, i) => { const ownerEntry = owners.find((x) => x.manifest && resolve(x.manifest.path) === resolve(registration.path)); const owner = ownerEntry?.manifest; const pathExists = existsSync(registration.path); let clean; let operation; let probeFailed = false; if (pathExists) { const status = run(registration.path, ["status", "--porcelain=v1", "-z"], "status", probe); if (!status.ok) probeFailed = true; else { clean = status.stdout.length === 0; for (const marker of ["MERGE_HEAD", "CHERRY_PICK_HEAD", "REVERT_HEAD", "rebase-merge", "rebase-apply", "sequencer"]) { const x = run(registration.path, ["rev-parse", "--git-path", marker], "rev-parse", probe); if (!x.ok) { probeFailed = true; break; } if (existsSync(x.stdout.trim())) { operation = marker; break; } } } } return publicFact({ registration, main: i === 0 || resolve(registration.path) === root, owner, pathExists, active: activeProcessCwds.some((x) => resolve(x) === resolve(registration.path) || resolve(x).startsWith(`${resolve(registration.path)}/`)), clean, operation, probeFailed, identity: ownerEntry?.legacy ? undefined : identity(root, registration, owner, probe) }); }); for (const entry of owners) if (entry.invalid) facts.push(publicFact({ owner: null, pathExists: false, mismatch: true, registration: { path: resolve(root, ".state/worktree-lifecycle/leases", `${entry.id}.json`) } })); else if (!registrations.some((r) => resolve(r.path) === resolve(entry.manifest.path))) facts.push(publicFact({ owner: entry.manifest, pathExists: existsSync(entry.manifest.path), registration: null, mismatch: entry.manifest.state !== "released", identity: false })); return facts; }
export async function reconcileManagedWorktrees({ originRoot, apply = false, activeProcessCwds = [], ttlMs, now, probe } = {}) { const items = await inventoryRepositoryWorktrees({ originRoot, activeProcessCwds, probe }); if (apply) for (const item of items.filter((x) => x.automaticAction === "release-worktree-only" && x.id)) { const entry = manifests(resolve(originRoot)).find((x) => x.manifest?.id === item.id); try { releaseManagedWorktree({ originRoot: resolve(originRoot), id: item.id, ownerToken: entry.manifest.ownerToken }); item.state = "released"; item.code = null; item.automaticAction = "none"; item.resources = "001"; } catch { item.state = "cleanup-debt"; item.code = "WORKTREE_CLEANUP_DEBT"; item.automaticAction = "none"; } } return { apply: Boolean(apply), items }; }
