import { createHash, randomBytes } from "node:crypto";
import { closeSync, constants, fsyncSync, fstatSync, lstatSync, mkdirSync, openSync, readFileSync, realpathSync, unlinkSync, writeFileSync, linkSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
const HASH = /^[a-f0-9]{64}$/; const HEAD = /^[a-f0-9]{40}$/;
const exact = (v, keys) => v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).length === keys.length && keys.every((k) => Object.hasOwn(v, k));
const fail = () => { throw Error("condition evidence must contain exactly known fields"); };
const canonical = (v) => Array.isArray(v) ? v.map(canonical) : v && typeof v === "object" ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, canonical(v[k])])) : v;
const hash = (v) => createHash("sha256").update(JSON.stringify(canonical(v))).digest("hex");
function identity(v, classifier = false) { if (!exact(v, ["goalId", "conditionId", "executionRevision", "executionContractHash", "conditionHash", "head", "adapter", "environment", "fixtures", "runId", "terminalProofHash", "artifact"])) fail(); if (![v.goalId, v.conditionId, v.runId].every((x) => typeof x === "string" && x) || !Number.isSafeInteger(v.executionRevision) || v.executionRevision < 1 || ![v.executionContractHash, v.conditionHash, v.terminalProofHash].every((x) => HASH.test(x)) || !HEAD.test(v.head)) fail(); if (!exact(v.adapter, ["ref", "version"]) || !exact(v.environment, ["ref", "fingerprint"]) || !Array.isArray(v.fixtures) || !exact(v.artifact, classifier ? ["id", "hash", "classifier"] : ["id", "hash"])) fail(); if (![v.adapter.ref, v.adapter.version, v.environment.ref, v.environment.fingerprint, v.artifact.id, v.artifact.hash].every((x) => typeof x === "string" && x) || !HASH.test(v.artifact.hash) || v.fixtures.some((f) => !exact(f, ["ref", "fingerprint"]) || typeof f.ref !== "string" || typeof f.fingerprint !== "string")) fail(); return v; }
export function normalizeConditionEvidence(input, expectedIdentity) { identity(expectedIdentity); identity(input, true); if (!exact(input.artifact.classifier, ["code"]) || typeof input.artifact.classifier.code !== "string" || !input.artifact.classifier.code) fail(); const actual = { ...input, artifact: { id: input.artifact.id, hash: input.artifact.hash } }; if (JSON.stringify(canonical(actual)) !== JSON.stringify(canonical(expectedIdentity))) throw Error("condition evidence identity mismatch"); return Object.freeze(structuredClone(input)); }
export function deriveObservationVerdict(evidence, { expectedIdentity, resolvedClassifier } = {}) { if (!expectedIdentity) throw Error("expected identity required"); const e = normalizeConditionEvidence(evidence, expectedIdentity); if (!exact(resolvedClassifier, ["code", "outcome"]) || resolvedClassifier.code !== e.artifact.classifier.code || !["passed", "failed", "inconclusive", "infrastructure_error"].includes(resolvedClassifier.outcome)) throw Error("trusted classifier required"); const evidenceId = hash(e); if (resolvedClassifier.outcome === "passed") return Object.freeze({ kind: "passed", evidenceId }); if (resolvedClassifier.outcome === "failed") return Object.freeze({ kind: "failed", evidenceId, failureCode: resolvedClassifier.code, findingFingerprint: hash({ conditionId: e.conditionId, evidenceId, code: resolvedClassifier.code }) }); if (resolvedClassifier.outcome === "infrastructure_error") return Object.freeze({ kind: "infrastructure_error", reason: resolvedClassifier.code }); return Object.freeze({ kind: "inconclusive", evidenceId, reason: resolvedClassifier.code }); }
function fileIdentity(path, text) { const before = lstatSync(path); if (!before.isFile() || before.isSymbolicLink() || before.nlink !== 1 || (before.mode & 0o777) !== 0o600 || before.size !== Buffer.byteLength(text)) throw Error("evidence file identity invalid"); const fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW); try { const opened = fstatSync(fd), data = readFileSync(fd, "utf8"), after = lstatSync(path); if (opened.dev !== before.dev || opened.ino !== before.ino || after.dev !== before.dev || after.ino !== before.ino || after.size !== before.size || after.mode !== before.mode || data !== text) throw Error("evidence file changed during read"); } finally { closeSync(fd); } }
function evidenceDir(stateRoot) { const input = resolve(stateRoot); if (typeof stateRoot !== "string" || lstatSync(input).isSymbolicLink()) throw Error("unsafe state root"); const root = realpathSync(input); const d = join(root, "condition-evidence"); try { mkdirSync(d, { recursive: false, mode: 0o700 }); } catch (error) { if (error?.code !== "EEXIST") throw error; } const s = lstatSync(d); if (!s.isDirectory() || s.isSymbolicLink() || (s.mode & 0o777) !== 0o700 || realpathSync(dirname(d)) !== root) throw Error("evidence directory invalid"); return d; }
function syncPath(path, flags = constants.O_RDONLY) { const fd = openSync(path, flags | constants.O_NOFOLLOW); try { fsyncSync(fd); } finally { closeSync(fd); } }
export function materializeConditionEvidence({ stateRoot, evidence, expectedIdentity } = {}) { if (typeof stateRoot !== "string") fail(); const normalized = normalizeConditionEvidence(evidence, expectedIdentity), id = hash(normalized), text = JSON.stringify(canonical(normalized)), d = evidenceDir(stateRoot), path = join(d, `${id}.json`); if (dirname(path) !== d) throw Error("unsafe evidence path"); try { fileIdentity(path, text); return Object.freeze({ evidenceId: id, path }); } catch (error) { if (error?.code !== "ENOENT") throw error; }
  const tmp = join(d, `.${id}.${process.pid}.${randomBytes(12).toString("hex")}`); try { writeFileSync(tmp, text, { mode: 0o600, flag: "wx" }); fileIdentity(tmp, text); syncPath(tmp); linkSync(tmp, path); unlinkSync(tmp); fileIdentity(path, text); syncPath(d, constants.O_RDONLY); return Object.freeze({ evidenceId: id, path }); } catch (error) { if (error?.code === "EEXIST") { try { unlinkSync(tmp); } catch {} fileIdentity(path, text); return Object.freeze({ evidenceId: id, path }); } throw error; } finally { try { unlinkSync(tmp); } catch {} }
}
