import { execFileSync } from "node:child_process";

const match = (pattern, path) => typeof pattern === "string" && typeof path === "string" && (pattern.endsWith("/**") ? (path === pattern.slice(0, -3) || path.startsWith(pattern.slice(0, -2))) : path === pattern);
const rows = (value) => value instanceof Map ? [...value.values()] : Array.isArray(value) ? value : [];
const get = (value, id) => value instanceof Map ? value.get(id) : rows(value).find((x) => x?.definition?.id === id || x?.id === id);
const equal = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const relative = (path) => typeof path === "string" && path && !path.includes("\0") && !path.startsWith("/") && !path.split("/").some((part) => !part || part === "." || part === "..") && !/^[A-Za-z]:/.test(path);
function defaultGit(root, args) { return execFileSync("git", args, { cwd: root, encoding: "buffer", stdio: ["ignore", "pipe", "ignore"] }); }
function current(rows, ref) { const found = rows.filter((x) => x?.ref === ref); return found.length === 1 ? found[0] : null; }
function taskMutation(projection, id) { const facts = projection?.taskMutationSequences; const fact = facts instanceof Map ? facts.get(id) : facts && typeof facts === "object" ? facts[id] : undefined; return Number.isSafeInteger(fact) ? fact : null; }
function taskFresh(evidence, definition, projection) { const ids = definition?.invalidation?.task_ids; if (!Array.isArray(ids)) return false; if (!ids.length) return true; if (!Number.isSafeInteger(evidence?.mutationSequence)) return false; return ids.every((id) => typeof id === "string" && taskMutation(projection, id) !== null && evidence.mutationSequence >= taskMutation(projection, id)); }
function stability(condition, evidence, projection) { const ids = condition.supportingEvidenceIds; const policy = condition.definition?.stability; const latestMutation = projection?.mutationSequence; if (!Array.isArray(ids) || !ids.length || new Set(ids).size !== ids.length || !policy || !Number.isSafeInteger(latestMutation)) return false; const selected = ids.map((id) => evidence.find((row) => row.evidenceId === id)); const conditionHash = condition.conditionHash;
  if (selected.some((row) => !row || row.verdict?.kind !== "passed" || row.conditionId !== condition.definition.id || row.executionRevision !== projection.executionRevision || row.executionContractHash !== projection.executionContractHash || typeof conditionHash !== "string" || row.conditionHash !== conditionHash || !Number.isSafeInteger(row.sequence) || !Number.isSafeInteger(row.mutationSequence) || row.mutationSequence > latestMutation)) return false;
  for (let i = 1; i < selected.length; i++) if (selected[i].sequence <= selected[i - 1].sequence) return false;
  if (policy.mode === "single") return selected.length === 1 && (!policy.require_fresh_environment || !!selected[0].environment?.fingerprint);
  if (policy.mode !== "consecutive" || !Number.isSafeInteger(policy.count) || selected.length !== policy.count) return false;
  if (selected.some((row, i) => i && row.sequence !== selected[i - 1].sequence + 1)) return false;
  return !policy.require_distinct_environment || new Set(selected.map((row) => `${row.environment?.ref}\0${row.environment?.fingerprint}`)).size === selected.length;
}
function identityFresh(evidence, condition, projection, world) { if (!evidence || evidence.executionRevision !== projection.executionRevision || evidence.executionContractHash !== projection.executionContractHash || typeof condition.conditionHash !== "string" || evidence.conditionHash !== condition.conditionHash || !/^[a-f0-9]{40}$/.test(evidence.head) || !/^[a-f0-9]{64}$/.test(evidence.terminalProofHash) || !evidence.artifact?.id || !/^[a-f0-9]{64}$/.test(evidence.artifact?.hash)) return false;
  const adapter = current(world.adapters, evidence.adapter?.ref), environment = current(world.environments, evidence.environment?.ref); if (!adapter || adapter.version !== evidence.adapter?.version || !environment || !environment.available || environment.fingerprint !== evidence.environment?.fingerprint) return false;
  if (!Array.isArray(evidence.fixtures) || new Set(evidence.fixtures.map((x) => x.ref)).size !== evidence.fixtures.length) return false; for (const fixture of evidence.fixtures) { const now = current(world.fixtures, fixture.ref); if (!now || !now.available || now.fingerprint !== fixture.fingerprint) return false; }
  if (evidence.resource) { const found = (world.resources || []).filter((x) => x?.key === evidence.resource.key); if (found.length !== 1 || !equal(found[0], evidence.resource)) return false; }
  if (!evidence.run || typeof evidence.run.runId !== "string" || evidence.run.state !== "terminal") return false; if ((world.activeRuns || []).some((run) => run.runId === evidence.run.runId)) return false;
  return true;
}
function gitPaths(root, oldHead, newHead, git) { try { git(root, ["merge-base", "--is-ancestor", oldHead, newHead]); } catch (error) { return error?.status === 1 ? false : null; }
  try { const raw = git(root, ["diff", "--name-status", "-z", "--find-renames", `${oldHead}..${newHead}`]); const buffer = Buffer.isBuffer(raw) ? raw : Buffer.from(raw); const tokens = buffer.toString("binary").split("\0").map((part) => Buffer.from(part, "binary")); const paths = [];
    for (let i = 0; i < tokens.length - 1;) { const status = tokens[i++].toString("utf8"); if (!status || !/^[ACDMRTUXB][0-9]*$/.test(status)) return null; const count = /^[RC]/.test(status) ? 2 : 1; if (i + count > tokens.length) return null; for (let n = 0; n < count; n++) { const pathBuffer = tokens[i++], path = pathBuffer.toString("utf8"); if (!Buffer.from(path).equals(pathBuffer) || !relative(path)) return null; paths.push(path); } }
    return paths;
  } catch { return null; }
}
function worldFresh(evidence, definition, projection, world, git) { const repo = world.repo; if (!repo || repo.sequencer || !Array.isArray(repo.trackedDirty) || !Array.isArray(repo.untracked) || repo.trackedDirty.length || repo.untracked.length || !evidence.head || !repo.head || typeof repo.root !== "string" || !repo.root.startsWith("/") || repo.root.includes("\0")) return false; if (!taskFresh(evidence, definition, projection)) return false; if (evidence.head === repo.head) return true; const paths = gitPaths(repo.root, evidence.head, repo.head, git); if (!Array.isArray(paths)) return false; const invalidation = definition.invalidation; if (!invalidation || !Array.isArray(invalidation.paths)) return false; return !paths.some((path) => !invalidation.paths.length || invalidation.paths.some((pattern) => match(pattern, path)));
}
export function evaluateConditionGraph({ projection, worldSnapshot, gitRunner = defaultGit } = {}) { const source = projection?.conditions; const evidence = Array.isArray(projection?.evidenceHistory) ? projection.evidenceHistory : []; const conditions = new Map(), visiting = new Set(); const evaluate = (id) => { if (conditions.has(id)) return conditions.get(id); if (visiting.has(id)) return { status: "stale", reason: "condition-cycle" }; visiting.add(id); const condition = get(source, id); let out = { status: "stale", reason: "incomplete-proof" }; if (condition && worldSnapshot?.safe === true && typeof gitRunner === "function") { const latestId = condition.supportingEvidenceIds?.at(-1), latest = evidence.find((row) => row.evidenceId === latestId); const predecessors = condition.definition?.depends_on; const dependenciesFresh = Array.isArray(predecessors) && predecessors.every((edge) => edge?.kind !== "condition" || evaluate(edge.id).status === "fresh"); if (!dependenciesFresh) out = { status: "stale", reason: "predecessor-stale" }; else if (!identityFresh(latest, condition, projection, worldSnapshot)) out = { status: "stale", reason: "identity-drift" }; else if (!worldFresh(latest, condition.definition, projection, worldSnapshot, gitRunner)) out = { status: "stale", reason: "world-drift" }; else if (!stability(condition, evidence, projection)) out = { status: "stale", reason: "stability-unproven" }; else out = { status: "fresh", reason: null }; }
  visiting.delete(id); conditions.set(id, out); return out; };
  for (const condition of rows(source)) if (condition?.definition?.id) evaluate(condition.definition.id);
  const oldApplicability = projection?.taskApplicability instanceof Map ? projection.taskApplicability : new Map(); const taskApplicability = new Map([...oldApplicability].map(([id, value]) => [id, { ...value, executionRevision: projection?.executionRevision }])); const tasks = projection?.tasks instanceof Map ? new Map(projection.tasks) : new Map(rows(projection?.tasks).map((task) => [task.id, task])); return Object.freeze({ conditions, tasks, taskApplicability });
}
